### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by yougotwill** [phil294/git-log--graph#16]
This feature might be overkill but could be useful for users with specific needs that aren't required to be a part of the extension. My need for this is that I can't read the full commit information and I'm happy to have horizontal overflow with a scrollbar so I can read everything. Obviously not everyone would want this and I don't think that it should be part of the extension - there are various solutions to the original problem that are better.

By allowing user customization via css I can solve my quick UI issues without bothering you and if I made CSS that was useful enough I could potentially make a PR at a later stage after testing things myself in my own machine.

Example:

Before:

https://github.com/phil294/git-log--graph/assets/14887287/96af4b92-a426-4879-95e2-fb0a23ea8a6f

After:

https://github.com/phil294/git-log--graph/assets/14887287/bbb350a3-5394-44c4-ae1e-3d3af0cfc048

CSS:

```css
.vue-recycle-scroller.direction-vertical .vue-recycle-scroller__item-wrapper {
    width: 150vw;
    overflow-x: scroll;
}
```
